### ISSUE TITLE
Display addresses for the address form in contract creation

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-front#34]
Currently, user have to copy and past the address. It will be more user friendly to also allow the user to select the address in a list of already used addresses.

**Comment by satello** [comment]
The users browser should cache already previously used inputs for all the fields

**Comment by clesaege** [comment]
I mean not the browser addresses, but the one used by the web3 provider. A bit like in Parity when you have to enter an address you get a list of all addresses which are watched.
