### ISSUE TITLE
Put security icons in contract creation.

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-front#35]
For partyB, there is no security icon relative to the address.
We should display the security icon, which will lower the chances the user input a wrong address with a bad Copy and Paste.

**Comment by satello** [comment]
What do you mean by security icon? Are you thinking something like a check mark if the address meets our criteria for being valid?

**Comment by clesaege** [comment]
No, a security icon which is a graphic representation of an address where changing 1bit of the address changes the whole icon.
Like the one we have in the top left corner.
![secicon](https://user-images.githubusercontent.com/8873352/33762211-f7ab43de-dc0b-11e7-86df-2eaf183c524b.png)

**Comment by M-ZubairAhmed** [comment]
Is this issue completed?
