### ISSUE TITLE
Improve UI for evidence

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-front#45]
Currently pieces of evidence appear on by line.
We could use a bullet list or a table for it to be cleaner and more user friendly.

**Comment by clesaege** [comment]
I'm speaking about the submit evidence UI (not the one for jurors).
@rominak Could you make a invision prototype for that?

**Comment by dboudro** [comment]
Has this been fixed? (see screenshots below)
![screen shot 2017-12-18 at 4 59 57 pm](https://user-images.githubusercontent.com/4648917/34098668-16444980-e418-11e7-941d-917670d6e3fb.png)
![screen shot 2017-12-18 at 5 00 04 pm](https://user-images.githubusercontent.com/4648917/34098670-17d1e000-e418-11e7-9bd5-25a75602561a.png)

**Comment by n1c01a5** [comment]
@dboudro no if it is possible I prefer a flat design no modals
