### ISSUE TITLE
Make the timeout understandable

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-front#46]
Currently users have no idea what the timeout is.
It should be understood that it is in second and that it is the time a party can take to answer when a dispute is made. Putting a default value would be a good idea.

**Comment by clesaege** [comment]
@rominak Could you make a invision prototype of the contract creation including that.

**Comment by clesaege** [comment]
After the contract is created, the display should be in the format D days, H hours, M minutes and S seconds.
(Only displaying the variables which are relevant)

**Comment by pazuzu111** [comment]
can you post links to the file that holds these issues so its easier to find
