### ISSUE TITLE
Improve "Getting started" documentation

### ISSUE THREAD

**Issue by RadValentin** [kleros/kleros-front#50]
## Need
Make it easier for devs to contribute to Kleros

## TODO
- Go through the steps of making a contribution (setup, code, tests, PR, merge)
- Document the process and make sure every step is covered in the "Getting started" section

**Comment by n1c01a5** [comment]
we have this document https://github.com/kleros/kleros.md/blob/master/quality-management/contributing.md but yes it would be to add a `contributing.md` doc in each repo

**Comment by RadValentin** [comment]
Sounds good. I'll add a link to that [doc](https://github.com/kleros/kleros.md/blob/master/quality-management/contributing.md) so it's easier for people to find it. My current plan is to focus on this repo and see what it's like to make a contribution. Later on we can extend the effort to cover all repos.

**Comment by rowlandekemezie** [comment]
@RadValentin Is this something you're working on currently? Can I add the links to the `Getting Started`?

**Comment by RadValentin** [comment]
@mentrie I'll submit a PR for this today, thanks!
