### ISSUE TITLE
Missing implementation

### ISSUE THREAD

**Issue by BernabeFelix** [kleros/kleros-front#66]
The following reducers are not implemented
- `src/redux/disputes/reducers.js`
- [ ] submitRuling
- [ ] rulingSubmitted
- [ ] rulingFailed

The following actions are not being dispatched
- `src/redux/disputes/actions.js`
- [x]  failureCaseData

The following actions creators are not implemented
- `src/redux/contracts/action-creators.js`
- [x]  deployRNG
- [x]  deployPinakion
- [x] deployKleros
- [x] configureKleros

I think that some of these are going to be implemented in the future, which ones should be deleted?

**Comment by satello** [comment]
We can delete `deployRNG`, `deployPinakion`, `deployKleros` and `configureKleros`. They were created mostly for testing purposes. All of these contracts are already deployed on the chain and I think there are no immediate plans to implement a feature for users to deploy a new arbitrator though the UI

**Comment by BernabeFelix** [comment]
Thank you @satello, should we keep actions and reducers?

**Comment by satello** [comment]
No we can clean those up as well if they aren't used elsewhere

**Comment by BernabeFelix** [comment]
@n1c01a5 @satello I think I didn't explain myself very well. 
The reducers are not implemented but its actions are been dispatched, they can be used, I just need to combine them. Is that ok? or should I delete them along with its actions?

**Comment by n1c01a5** [comment]
@BernabeFelix yes I think it's not good to have actions without reducers. For these reducers, see with @satello

**Comment by satello** [comment]
@BernabeFelix Having reducers for all actions is ideal. Are the actions with missing reducers being dispatched from the `actions-creator` functions you deleted? If so you can delete the corresponding actions/reducers unless they are used in another `action-creator`. If the action is being used but does not have a reducer in general it is good to make a reducer for it. Not sure if that is in scope of what you are working on or not. If you have questions about specific actions/reducers you can comment the file/line number and I can take a look for you
